/**
 * Shop Menu Icons Utility
 * 
 * Shared icon mapping for both desktop mega menu and mobile menu.
 * Maps category/item names to Lucide React icons.
 */

import { 
  Sparkles, 
  Coffee, 
  Bone, 
  Brain, 
  Heart, 
  Activity, 
  Apple, 
  Zap, 
  Shield, 
  Pill, 
  Utensils, 
  Dog, 
  Moon, 
  Smile, 
  Droplet, 
  Eye, 
  Scale, 
  MoreHorizontal, 
  Wind, 
  Dumbbell, 
  Circle, 
  RefreshCw, 
  TrendingUp, 
  TrendingDown, 
  AlertCircle, 
  Flame, 
  BatteryLow, 
  ShieldCheck, 
  Package, 
  HeartPulse 
} from 'lucide-react';

export const getIconForItem = (item: string) => {
  const iconMap: Record<string, any> = {
    // Categories
    'Anti-Aging': Sparkles,
    'Antioxidants': Shield,
    'Beauty': Sparkles,
    'Beverages': Coffee,
    'Bone & Skeletal Health': Bone,
    'Brain Health': Brain,
    'Cardiovascular Health': HeartPulse,
    'Circulation': Activity,
    'Digestive Health': Apple,
    'Energy': Zap,
    'Immune Health': ShieldCheck,
    'Individual Vitamins & Minerals': Pill,
    'Joint Health': Activity,
    'Meals & Proteins': Utensils,
    'Multivitamins': Package,
    'Pet Products': Dog,
    'Sleep & Relaxation': Moon,
    'Stress & Mood': Smile,
    'Sweeteners': Droplet,
    'Vision Health': Eye,
    'Weight Management': Scale,
    'Other': MoreHorizontal,
    
    // Body Part
    'Arteries': Activity,
    'Bladder': Circle,
    'Blood': Droplet,
    'Bones': Bone,
    'Brain': Brain,
    'Breast': Circle,
    'Colon': Circle,
    'Ears': Circle,
    'Eyes': Eye,
    'Endocrine System': Circle,
    'GI Tract': Apple,
    'Hair, Skin, & Nails': Sparkles,
    'Heart': Heart,
    'Immune System': Shield,
    'Joints': Activity,
    'Kidneys': Circle,
    'Legs': Activity,
    'Liver': Circle,
    'Lungs': Wind,
    'Muscles': Dumbbell,
    'Nerves': Brain,
    'Prostate': Circle,
    'Reproductive System': Circle,
    'Stomach': Apple,
    'Urinary Tract': Circle,
    'Veins': Activity,
    
    // Body Function
    'Breathing or Respiration': Wind,
    'Cell protection': Shield,
    'Circulation': Activity,
    'Cognitive Function': Brain,
    'Detoxification': RefreshCw,
    'Digestion': Apple,
    'Energy Production': Zap,
    'Hormone Balancing': Scale,
    'Immune Defense': ShieldCheck,
    'Memory': Brain,
    'Metabolism': TrendingUp,
    'Mood Balancing': Smile,
    'Movement': Activity,
    'Skin Protection': Sparkles,
    'Sleep': Moon,
    'Structural Support': Bone,
    'Urinary Function': Circle,
    'Vision': Eye,
    'Waste Removal': RefreshCw,
    
    // Health Issues
    'Joint Pain and Stiffness': Activity,
    'Heart and Blood Vessel Health': HeartPulse,
    'High Blood Pressure': HeartPulse,
    'Type 2 Diabetes': Droplet,
    'Cholesterol Management': TrendingDown,
    'Anxiety and Stress': AlertCircle,
    'Depression': Smile,
    'Memory and Brain Health': Brain,
    'Sleep Disorders': Moon,
    'Immune Health': ShieldCheck,
    'Bone Strength': Bone,
    'Vision Problems': Eye,
    'Fatigue': BatteryLow,
    'Menopause Symptoms': Circle,
    'Liver Health': Circle,
    'Urinary Tract Infections': Circle,
    'Digestive Health': Apple,
    'Breathing Problems': Wind,
  };

  return iconMap[item] || Circle;
};
